apiVersion: v1
kind: ConfigMap
metadata:
  name: xp-springboot-mysql-configmap
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://xp-mysql.default.svc.cluster.local:3306/orders?useSSL=false&serverTimezone=UTC"