apiVersion: v1
kind: Service
metadata:
  name: xp-springboot-mysql-service
spec:
  selector:
    app: xp-springboot-mysql
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer