apiVersion: apps/v1
kind: Deployment
metadata:
  name: xp-springboot-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xp-springboot-mysql
  template:
    metadata:
      labels:
        app: xp-springboot-mysql
    spec:
      containers:
        - name: xp-springboot-mysql
          image: xp-springboot-mysql:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: xp-springboot-mysql-configmap
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: xp-springboot-mysql-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: xp-springboot-mysql-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            # This given to us from Helm chart
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: xp-redis
                  key: redis-password
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: xp-springboot-mysql-secrets
                  key: KAFKA_SASL_USERNAME
            # This given to us from Helm chart
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: xp-kafka-user-passwords
                  key: client-passwords
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
